# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'KnowGod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KnowGod
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
end
